project:
  type: website
  output-dir: docs

website:
  title: "Asreview Academy"
  favicon: "docs/images/ASReviewLAB/Elas_afstudeerhoedje.png"

  sidebar:
   background: "#FDCB25" #5287C6
   logo: "docs/images/ASReviewLAB/Elas_afstudeerhoedje.png"
   pinned: true
   align: left
   tools:
     - icon: github
       href: https://github.com/asreview/asreview-academy/
       text: "GitHub organization"
   style: "docked"
   search: true
   collapse-level: 1
   contents:
     - href: index.qmd
       text: Home
     # - href: about.qmd
     #   text: About
     - section: "Introduction Courses"
       contents:
         - href: ASReviewLAB.qmd
           text: ASReview LAB
         - href: datatools.qmd
           text: Datatools
         - href: simulation.qmd
           text: Simulation Mode
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



